// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Which physical camera a feed comes from.
enum CameraLens: Int {
  case back = 0
  case front = 1
}

/// Corner the picture-in-picture inset is anchored to.
enum InsetCorner: Int {
  case topLeft = 0
  case topRight = 1
  case bottomLeft = 2
  case bottomRight = 3
}

/// Composition layout of the two feeds.
enum DualLayoutMode: Int {
  /// Primary full-frame, secondary as a rounded inset.
  case pictureInPicture = 0
  /// Two equal halves, stacked vertically.
  case splitVertical = 1
  /// Two equal halves, side by side.
  case splitHorizontal = 2
}

/// Target capture resolution (the hardware caps this; 720p is the safe ceiling
/// for Android concurrent cameras).
enum DualResolution: Int {
  case sd480 = 0
  case hd720 = 1
  case hd1080 = 2
}

/// Recorded video codec.
enum VideoCodec: Int {
  case h264 = 0
  case hevc = 1
}

/// Thermal pressure buckets, normalized across platforms.
enum ThermalLevel: Int {
  case nominal = 0
  case fair = 1
  case serious = 2
  case critical = 3
}

/// Why a capability probe failed, when it did.
enum UnsupportedReason: Int {
  /// The device hardware cannot run front+back concurrently.
  case noConcurrentCamera = 0
  /// The OS version is too old for the multi-cam API.
  case osTooOld = 1
  /// Camera permission has not been granted.
  case permissionDenied = 2
}

/// Result of probing whether this device can run the dual-camera pipeline.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CameraCapabilities {
  var isSupported: Bool
  /// Max composite width the device can sustain concurrently (null if unknown).
  var maxWidth: Int64? = nil
  var maxHeight: Int64? = nil
  /// Populated only when [isSupported] is false.
  var reason: UnsupportedReason? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CameraCapabilities? {
    let isSupported = pigeonVar_list[0] as! Bool
    let maxWidth: Int64? = nilOrValue(pigeonVar_list[1])
    let maxHeight: Int64? = nilOrValue(pigeonVar_list[2])
    let reason: UnsupportedReason? = nilOrValue(pigeonVar_list[3])

    return CameraCapabilities(
      isSupported: isSupported,
      maxWidth: maxWidth,
      maxHeight: maxHeight,
      reason: reason
    )
  }
  func toList() -> [Any?] {
    return [
      isSupported,
      maxWidth,
      maxHeight,
      reason,
    ]
  }
}

/// The picture-in-picture / split geometry. Computed once in Dart and applied
/// identically to preview, recording, and stills so they can never drift.
///
/// Generated class from Pigeon that represents data sent in messages.
struct LayoutConfig {
  var mode: DualLayoutMode
  /// Which lens is full-frame (PiP) / first half (split).
  var primary: CameraLens
  var insetCorner: InsetCorner
  /// Inset size as a fraction of the full frame's shorter side (PiP only).
  var insetScale: Double
  /// Inset corner radius in logical px (PiP only).
  var cornerRadius: Double
  /// Inset margin from the anchored corner in logical px (PiP only).
  var margin: Double
  /// Whether the front feed is horizontally mirrored (selfie convention).
  var mirrorFront: Bool
  /// PiP inset is a centered circle instead of a rounded rectangle (PiP only).
  var circleInset: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LayoutConfig? {
    let mode = pigeonVar_list[0] as! DualLayoutMode
    let primary = pigeonVar_list[1] as! CameraLens
    let insetCorner = pigeonVar_list[2] as! InsetCorner
    let insetScale = pigeonVar_list[3] as! Double
    let cornerRadius = pigeonVar_list[4] as! Double
    let margin = pigeonVar_list[5] as! Double
    let mirrorFront = pigeonVar_list[6] as! Bool
    let circleInset = pigeonVar_list[7] as! Bool

    return LayoutConfig(
      mode: mode,
      primary: primary,
      insetCorner: insetCorner,
      insetScale: insetScale,
      cornerRadius: cornerRadius,
      margin: margin,
      mirrorFront: mirrorFront,
      circleInset: circleInset
    )
  }
  func toList() -> [Any?] {
    return [
      mode,
      primary,
      insetCorner,
      insetScale,
      cornerRadius,
      margin,
      mirrorFront,
      circleInset,
    ]
  }
}

/// Everything needed to bring the pipeline up.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RecordingConfig {
  var layout: LayoutConfig
  var resolution: DualResolution
  var codec: VideoCodec
  var recordAudio: Bool
  /// Hard cap on recording length; 0 = no cap (the ThermalGovernor may still
  /// stop earlier).
  var maxDurationMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RecordingConfig? {
    let layout = pigeonVar_list[0] as! LayoutConfig
    let resolution = pigeonVar_list[1] as! DualResolution
    let codec = pigeonVar_list[2] as! VideoCodec
    let recordAudio = pigeonVar_list[3] as! Bool
    let maxDurationMs = pigeonVar_list[4] as! Int64

    return RecordingConfig(
      layout: layout,
      resolution: resolution,
      codec: codec,
      recordAudio: recordAudio,
      maxDurationMs: maxDurationMs
    )
  }
  func toList() -> [Any?] {
    return [
      layout,
      resolution,
      codec,
      recordAudio,
      maxDurationMs,
    ]
  }
}

/// Live performance telemetry for the debug HUD (ARCHITECTURE.md §10).
///
/// Generated class from Pigeon that represents data sent in messages.
struct FrameStats {
  /// Composited frames per second over the last window.
  var fps: Double
  /// Mean GPU composite time in ms over the last window (target < 16).
  var compositeMs: Double
  /// Frames dropped at the encoder boundary since recording began.
  var droppedFrames: Int64
  var thermal: ThermalLevel


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FrameStats? {
    let fps = pigeonVar_list[0] as! Double
    let compositeMs = pigeonVar_list[1] as! Double
    let droppedFrames = pigeonVar_list[2] as! Int64
    let thermal = pigeonVar_list[3] as! ThermalLevel

    return FrameStats(
      fps: fps,
      compositeMs: compositeMs,
      droppedFrames: droppedFrames,
      thermal: thermal
    )
  }
  func toList() -> [Any?] {
    return [
      fps,
      compositeMs,
      droppedFrames,
      thermal,
    ]
  }
}

/// Returned by [initialize]; the texture id renders via Flutter's `Texture`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct InitResult {
  var textureId: Int64
  var capabilities: CameraCapabilities


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InitResult? {
    let textureId = pigeonVar_list[0] as! Int64
    let capabilities = pigeonVar_list[1] as! CameraCapabilities

    return InitResult(
      textureId: textureId,
      capabilities: capabilities
    )
  }
  func toList() -> [Any?] {
    return [
      textureId,
      capabilities,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CameraLens(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return InsetCorner(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DualLayoutMode(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DualResolution(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VideoCodec(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ThermalLevel(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return UnsupportedReason(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      return CameraCapabilities.fromList(self.readValue() as! [Any?])
    case 137:
      return LayoutConfig.fromList(self.readValue() as! [Any?])
    case 138:
      return RecordingConfig.fromList(self.readValue() as! [Any?])
    case 139:
      return FrameStats.fromList(self.readValue() as! [Any?])
    case 140:
      return InitResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CameraLens {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? InsetCorner {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? DualLayoutMode {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? DualResolution {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? VideoCodec {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? ThermalLevel {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? UnsupportedReason {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? CameraCapabilities {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? LayoutConfig {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? RecordingConfig {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? FrameStats {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? InitResult {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Commands: Dart -> native.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DualCameraHostApi {
  /// Probe hardware support without bringing the pipeline up.
  func probeSupport(completion: @escaping (Result<CameraCapabilities, Error>) -> Void)
  /// Bring up the session + compositor; returns the preview texture id.
  func initialize(config: RecordingConfig, completion: @escaping (Result<InitResult, Error>) -> Void)
  func startRecording(completion: @escaping (Result<Void, Error>) -> Void)
  /// Returns the path to the finished composited .mp4.
  func stopRecording(completion: @escaping (Result<String, Error>) -> Void)
  /// Returns the path to a composited still (JPEG/HEIC).
  func takePhoto(completion: @escaping (Result<String, Error>) -> Void)
  /// Flip which feed is full-frame, live.
  func swapPrimary(completion: @escaping (Result<Void, Error>) -> Void)
  /// Update layout geometry live (e.g. user drags the inset).
  func setLayout(layout: LayoutConfig, completion: @escaping (Result<Void, Error>) -> Void)
  func dispose(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DualCameraHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `DualCameraHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DualCameraHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Probe hardware support without bringing the pipeline up.
    let probeSupportChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.probeSupport\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      probeSupportChannel.setMessageHandler { _, reply in
        api.probeSupport { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      probeSupportChannel.setMessageHandler(nil)
    }
    /// Bring up the session + compositor; returns the preview texture id.
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! RecordingConfig
        api.initialize(config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let startRecordingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.startRecording\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startRecordingChannel.setMessageHandler { _, reply in
        api.startRecording { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startRecordingChannel.setMessageHandler(nil)
    }
    /// Returns the path to the finished composited .mp4.
    let stopRecordingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.stopRecording\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopRecordingChannel.setMessageHandler { _, reply in
        api.stopRecording { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopRecordingChannel.setMessageHandler(nil)
    }
    /// Returns the path to a composited still (JPEG/HEIC).
    let takePhotoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.takePhoto\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      takePhotoChannel.setMessageHandler { _, reply in
        api.takePhoto { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      takePhotoChannel.setMessageHandler(nil)
    }
    /// Flip which feed is full-frame, live.
    let swapPrimaryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.swapPrimary\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      swapPrimaryChannel.setMessageHandler { _, reply in
        api.swapPrimary { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      swapPrimaryChannel.setMessageHandler(nil)
    }
    /// Update layout geometry live (e.g. user drags the inset).
    let setLayoutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.setLayout\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLayoutChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let layoutArg = args[0] as! LayoutConfig
        api.setLayout(layout: layoutArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setLayoutChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        api.dispose { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
/// State + telemetry: native -> Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol DualCameraFlutterApiProtocol {
  func onReady(textureId textureIdArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onError(code codeArg: String, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onRecordingStarted(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onRecordingStopped(path pathArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onCapabilityChanged(capabilities capabilitiesArg: CameraCapabilities, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onThermal(level levelArg: ThermalLevel, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onFrameStats(stats statsArg: FrameStats, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class DualCameraFlutterApi: DualCameraFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onReady(textureId textureIdArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onReady\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([textureIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onError(code codeArg: String, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([codeArg, messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onRecordingStarted(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onRecordingStarted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onRecordingStopped(path pathArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onRecordingStopped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([pathArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onCapabilityChanged(capabilities capabilitiesArg: CameraCapabilities, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onCapabilityChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([capabilitiesArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onThermal(level levelArg: ThermalLevel, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onThermal\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([levelArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onFrameStats(stats statsArg: FrameStats, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onFrameStats\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
