// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.romanslack.dual_camera_recorder_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Which physical camera a feed comes from. */
enum class CameraLens(val raw: Int) {
  BACK(0),
  FRONT(1);

  companion object {
    fun ofRaw(raw: Int): CameraLens? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Corner the picture-in-picture inset is anchored to. */
enum class InsetCorner(val raw: Int) {
  TOP_LEFT(0),
  TOP_RIGHT(1),
  BOTTOM_LEFT(2),
  BOTTOM_RIGHT(3);

  companion object {
    fun ofRaw(raw: Int): InsetCorner? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Composition layout of the two feeds. */
enum class DualLayoutMode(val raw: Int) {
  /** Primary full-frame, secondary as a rounded inset. */
  PICTURE_IN_PICTURE(0),
  /** Two equal halves, stacked vertically. */
  SPLIT_VERTICAL(1),
  /** Two equal halves, side by side. */
  SPLIT_HORIZONTAL(2);

  companion object {
    fun ofRaw(raw: Int): DualLayoutMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Target capture resolution (the hardware caps this; 720p is the safe ceiling
 * for Android concurrent cameras).
 */
enum class DualResolution(val raw: Int) {
  SD480(0),
  HD720(1),
  HD1080(2);

  companion object {
    fun ofRaw(raw: Int): DualResolution? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Recorded video codec. */
enum class VideoCodec(val raw: Int) {
  H264(0),
  HEVC(1);

  companion object {
    fun ofRaw(raw: Int): VideoCodec? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Thermal pressure buckets, normalized across platforms. */
enum class ThermalLevel(val raw: Int) {
  NOMINAL(0),
  FAIR(1),
  SERIOUS(2),
  CRITICAL(3);

  companion object {
    fun ofRaw(raw: Int): ThermalLevel? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Why a capability probe failed, when it did. */
enum class UnsupportedReason(val raw: Int) {
  /** The device hardware cannot run front+back concurrently. */
  NO_CONCURRENT_CAMERA(0),
  /** The OS version is too old for the multi-cam API. */
  OS_TOO_OLD(1),
  /** Camera permission has not been granted. */
  PERMISSION_DENIED(2);

  companion object {
    fun ofRaw(raw: Int): UnsupportedReason? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Result of probing whether this device can run the dual-camera pipeline.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CameraCapabilities (
  val isSupported: Boolean,
  /** Max composite width the device can sustain concurrently (null if unknown). */
  val maxWidth: Long? = null,
  val maxHeight: Long? = null,
  /** Populated only when [isSupported] is false. */
  val reason: UnsupportedReason? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CameraCapabilities {
      val isSupported = pigeonVar_list[0] as Boolean
      val maxWidth = pigeonVar_list[1] as Long?
      val maxHeight = pigeonVar_list[2] as Long?
      val reason = pigeonVar_list[3] as UnsupportedReason?
      return CameraCapabilities(isSupported, maxWidth, maxHeight, reason)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isSupported,
      maxWidth,
      maxHeight,
      reason,
    )
  }
}

/**
 * The picture-in-picture / split geometry. Computed once in Dart and applied
 * identically to preview, recording, and stills so they can never drift.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LayoutConfig (
  val mode: DualLayoutMode,
  /** Which lens is full-frame (PiP) / first half (split). */
  val primary: CameraLens,
  val insetCorner: InsetCorner,
  /** Inset size as a fraction of the full frame's shorter side (PiP only). */
  val insetScale: Double,
  /** Inset corner radius in logical px (PiP only). */
  val cornerRadius: Double,
  /** Inset margin from the anchored corner in logical px (PiP only). */
  val margin: Double,
  /** Whether the front feed is horizontally mirrored (selfie convention). */
  val mirrorFront: Boolean,
  /** PiP inset is a centered circle instead of a rounded rectangle (PiP only). */
  val circleInset: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LayoutConfig {
      val mode = pigeonVar_list[0] as DualLayoutMode
      val primary = pigeonVar_list[1] as CameraLens
      val insetCorner = pigeonVar_list[2] as InsetCorner
      val insetScale = pigeonVar_list[3] as Double
      val cornerRadius = pigeonVar_list[4] as Double
      val margin = pigeonVar_list[5] as Double
      val mirrorFront = pigeonVar_list[6] as Boolean
      val circleInset = pigeonVar_list[7] as Boolean
      return LayoutConfig(mode, primary, insetCorner, insetScale, cornerRadius, margin, mirrorFront, circleInset)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mode,
      primary,
      insetCorner,
      insetScale,
      cornerRadius,
      margin,
      mirrorFront,
      circleInset,
    )
  }
}

/**
 * Everything needed to bring the pipeline up.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RecordingConfig (
  val layout: LayoutConfig,
  val resolution: DualResolution,
  val codec: VideoCodec,
  val recordAudio: Boolean,
  /**
   * Hard cap on recording length; 0 = no cap (the ThermalGovernor may still
   * stop earlier).
   */
  val maxDurationMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RecordingConfig {
      val layout = pigeonVar_list[0] as LayoutConfig
      val resolution = pigeonVar_list[1] as DualResolution
      val codec = pigeonVar_list[2] as VideoCodec
      val recordAudio = pigeonVar_list[3] as Boolean
      val maxDurationMs = pigeonVar_list[4] as Long
      return RecordingConfig(layout, resolution, codec, recordAudio, maxDurationMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      layout,
      resolution,
      codec,
      recordAudio,
      maxDurationMs,
    )
  }
}

/**
 * Live performance telemetry for the debug HUD (ARCHITECTURE.md §10).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FrameStats (
  /** Composited frames per second over the last window. */
  val fps: Double,
  /** Mean GPU composite time in ms over the last window (target < 16). */
  val compositeMs: Double,
  /** Frames dropped at the encoder boundary since recording began. */
  val droppedFrames: Long,
  val thermal: ThermalLevel
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FrameStats {
      val fps = pigeonVar_list[0] as Double
      val compositeMs = pigeonVar_list[1] as Double
      val droppedFrames = pigeonVar_list[2] as Long
      val thermal = pigeonVar_list[3] as ThermalLevel
      return FrameStats(fps, compositeMs, droppedFrames, thermal)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fps,
      compositeMs,
      droppedFrames,
      thermal,
    )
  }
}

/**
 * Returned by [initialize]; the texture id renders via Flutter's `Texture`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class InitResult (
  val textureId: Long,
  val capabilities: CameraCapabilities
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InitResult {
      val textureId = pigeonVar_list[0] as Long
      val capabilities = pigeonVar_list[1] as CameraCapabilities
      return InitResult(textureId, capabilities)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      textureId,
      capabilities,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CameraLens.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          InsetCorner.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DualLayoutMode.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DualResolution.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VideoCodec.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ThermalLevel.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          UnsupportedReason.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CameraCapabilities.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LayoutConfig.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RecordingConfig.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FrameStats.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InitResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CameraLens -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is InsetCorner -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is DualLayoutMode -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is DualResolution -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is VideoCodec -> {
        stream.write(133)
        writeValue(stream, value.raw)
      }
      is ThermalLevel -> {
        stream.write(134)
        writeValue(stream, value.raw)
      }
      is UnsupportedReason -> {
        stream.write(135)
        writeValue(stream, value.raw)
      }
      is CameraCapabilities -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is LayoutConfig -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is RecordingConfig -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is FrameStats -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is InitResult -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Commands: Dart -> native.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface DualCameraHostApi {
  /** Probe hardware support without bringing the pipeline up. */
  fun probeSupport(callback: (Result<CameraCapabilities>) -> Unit)
  /** Bring up the session + compositor; returns the preview texture id. */
  fun initialize(config: RecordingConfig, callback: (Result<InitResult>) -> Unit)
  fun startRecording(callback: (Result<Unit>) -> Unit)
  /** Returns the path to the finished composited .mp4. */
  fun stopRecording(callback: (Result<String>) -> Unit)
  /** Returns the path to a composited still (JPEG/HEIC). */
  fun takePhoto(callback: (Result<String>) -> Unit)
  /** Flip which feed is full-frame, live. */
  fun swapPrimary(callback: (Result<Unit>) -> Unit)
  /** Update layout geometry live (e.g. user drags the inset). */
  fun setLayout(layout: LayoutConfig, callback: (Result<Unit>) -> Unit)
  fun dispose(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by DualCameraHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `DualCameraHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DualCameraHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.probeSupport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.probeSupport{ result: Result<CameraCapabilities> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as RecordingConfig
            api.initialize(configArg) { result: Result<InitResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.startRecording$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.startRecording{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.stopRecording$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopRecording{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.takePhoto$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.takePhoto{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.swapPrimary$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.swapPrimary{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.setLayout$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val layoutArg = args[0] as LayoutConfig
            api.setLayout(layoutArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.dispose{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * State + telemetry: native -> Dart.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class DualCameraFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by DualCameraFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onReady(textureIdArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onReady$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(textureIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onError(codeArg: String, messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(codeArg, messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onRecordingStarted(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onRecordingStarted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onRecordingStopped(pathArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onRecordingStopped$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(pathArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onCapabilityChanged(capabilitiesArg: CameraCapabilities, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onCapabilityChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(capabilitiesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onThermal(levelArg: ThermalLevel, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onThermal$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(levelArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onFrameStats(statsArg: FrameStats, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onFrameStats$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(statsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
