// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// Which physical camera a feed comes from.
enum CameraLens {
  back,
  front,
}

/// Corner the picture-in-picture inset is anchored to.
enum InsetCorner {
  topLeft,
  topRight,
  bottomLeft,
  bottomRight,
}

/// Composition layout of the two feeds.
enum DualLayoutMode {
  /// Primary full-frame, secondary as a rounded inset.
  pictureInPicture,
  /// Two equal halves, stacked vertically.
  splitVertical,
  /// Two equal halves, side by side.
  splitHorizontal,
}

/// Target capture resolution (the hardware caps this; 720p is the safe ceiling
/// for Android concurrent cameras).
enum DualResolution {
  sd480,
  hd720,
  hd1080,
}

/// Recorded video codec.
enum VideoCodec {
  h264,
  hevc,
}

/// Thermal pressure buckets, normalized across platforms.
enum ThermalLevel {
  nominal,
  fair,
  serious,
  critical,
}

/// Why a capability probe failed, when it did.
enum UnsupportedReason {
  /// The device hardware cannot run front+back concurrently.
  noConcurrentCamera,
  /// The OS version is too old for the multi-cam API.
  osTooOld,
  /// Camera permission has not been granted.
  permissionDenied,
}

/// Result of probing whether this device can run the dual-camera pipeline.
class CameraCapabilities {
  CameraCapabilities({
    required this.isSupported,
    this.maxWidth,
    this.maxHeight,
    this.reason,
  });

  bool isSupported;

  /// Max composite width the device can sustain concurrently (null if unknown).
  int? maxWidth;

  int? maxHeight;

  /// Populated only when [isSupported] is false.
  UnsupportedReason? reason;

  Object encode() {
    return <Object?>[
      isSupported,
      maxWidth,
      maxHeight,
      reason,
    ];
  }

  static CameraCapabilities decode(Object result) {
    result as List<Object?>;
    return CameraCapabilities(
      isSupported: result[0]! as bool,
      maxWidth: result[1] as int?,
      maxHeight: result[2] as int?,
      reason: result[3] as UnsupportedReason?,
    );
  }
}

/// The picture-in-picture / split geometry. Computed once in Dart and applied
/// identically to preview, recording, and stills so they can never drift.
class LayoutConfig {
  LayoutConfig({
    required this.mode,
    required this.primary,
    required this.insetCorner,
    required this.insetScale,
    required this.cornerRadius,
    required this.margin,
    required this.mirrorFront,
    required this.circleInset,
  });

  DualLayoutMode mode;

  /// Which lens is full-frame (PiP) / first half (split).
  CameraLens primary;

  InsetCorner insetCorner;

  /// Inset size as a fraction of the full frame's shorter side (PiP only).
  double insetScale;

  /// Inset corner radius in logical px (PiP only).
  double cornerRadius;

  /// Inset margin from the anchored corner in logical px (PiP only).
  double margin;

  /// Whether the front feed is horizontally mirrored (selfie convention).
  bool mirrorFront;

  /// PiP inset is a centered circle instead of a rounded rectangle (PiP only).
  bool circleInset;

  Object encode() {
    return <Object?>[
      mode,
      primary,
      insetCorner,
      insetScale,
      cornerRadius,
      margin,
      mirrorFront,
      circleInset,
    ];
  }

  static LayoutConfig decode(Object result) {
    result as List<Object?>;
    return LayoutConfig(
      mode: result[0]! as DualLayoutMode,
      primary: result[1]! as CameraLens,
      insetCorner: result[2]! as InsetCorner,
      insetScale: result[3]! as double,
      cornerRadius: result[4]! as double,
      margin: result[5]! as double,
      mirrorFront: result[6]! as bool,
      circleInset: result[7]! as bool,
    );
  }
}

/// Everything needed to bring the pipeline up.
class RecordingConfig {
  RecordingConfig({
    required this.layout,
    required this.resolution,
    required this.codec,
    required this.recordAudio,
    required this.maxDurationMs,
  });

  LayoutConfig layout;

  DualResolution resolution;

  VideoCodec codec;

  bool recordAudio;

  /// Hard cap on recording length; 0 = no cap (the ThermalGovernor may still
  /// stop earlier).
  int maxDurationMs;

  Object encode() {
    return <Object?>[
      layout,
      resolution,
      codec,
      recordAudio,
      maxDurationMs,
    ];
  }

  static RecordingConfig decode(Object result) {
    result as List<Object?>;
    return RecordingConfig(
      layout: result[0]! as LayoutConfig,
      resolution: result[1]! as DualResolution,
      codec: result[2]! as VideoCodec,
      recordAudio: result[3]! as bool,
      maxDurationMs: result[4]! as int,
    );
  }
}

/// Live performance telemetry for the debug HUD (ARCHITECTURE.md §10).
class FrameStats {
  FrameStats({
    required this.fps,
    required this.compositeMs,
    required this.droppedFrames,
    required this.thermal,
  });

  /// Composited frames per second over the last window.
  double fps;

  /// Mean GPU composite time in ms over the last window (target < 16).
  double compositeMs;

  /// Frames dropped at the encoder boundary since recording began.
  int droppedFrames;

  ThermalLevel thermal;

  Object encode() {
    return <Object?>[
      fps,
      compositeMs,
      droppedFrames,
      thermal,
    ];
  }

  static FrameStats decode(Object result) {
    result as List<Object?>;
    return FrameStats(
      fps: result[0]! as double,
      compositeMs: result[1]! as double,
      droppedFrames: result[2]! as int,
      thermal: result[3]! as ThermalLevel,
    );
  }
}

/// Returned by [initialize]; the texture id renders via Flutter's `Texture`.
class InitResult {
  InitResult({
    required this.textureId,
    required this.capabilities,
  });

  int textureId;

  CameraCapabilities capabilities;

  Object encode() {
    return <Object?>[
      textureId,
      capabilities,
    ];
  }

  static InitResult decode(Object result) {
    result as List<Object?>;
    return InitResult(
      textureId: result[0]! as int,
      capabilities: result[1]! as CameraCapabilities,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is CameraLens) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is InsetCorner) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is DualLayoutMode) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is DualResolution) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is VideoCodec) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is ThermalLevel) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is UnsupportedReason) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is CameraCapabilities) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is LayoutConfig) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is RecordingConfig) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is FrameStats) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is InitResult) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CameraLens.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : InsetCorner.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : DualLayoutMode.values[value];
      case 132: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : DualResolution.values[value];
      case 133: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : VideoCodec.values[value];
      case 134: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ThermalLevel.values[value];
      case 135: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : UnsupportedReason.values[value];
      case 136: 
        return CameraCapabilities.decode(readValue(buffer)!);
      case 137: 
        return LayoutConfig.decode(readValue(buffer)!);
      case 138: 
        return RecordingConfig.decode(readValue(buffer)!);
      case 139: 
        return FrameStats.decode(readValue(buffer)!);
      case 140: 
        return InitResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Commands: Dart -> native.
class DualCameraHostApi {
  /// Constructor for [DualCameraHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DualCameraHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Probe hardware support without bringing the pipeline up.
  Future<CameraCapabilities> probeSupport() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.probeSupport$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CameraCapabilities?)!;
    }
  }

  /// Bring up the session + compositor; returns the preview texture id.
  Future<InitResult> initialize(RecordingConfig config) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[config]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as InitResult?)!;
    }
  }

  Future<void> startRecording() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.startRecording$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Returns the path to the finished composited .mp4.
  Future<String> stopRecording() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.stopRecording$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  /// Returns the path to a composited still (JPEG/HEIC).
  Future<String> takePhoto() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.takePhoto$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  /// Flip which feed is full-frame, live.
  Future<void> swapPrimary() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.swapPrimary$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Update layout geometry live (e.g. user drags the inset).
  Future<void> setLayout(LayoutConfig layout) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.setLayout$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[layout]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> dispose() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraHostApi.dispose$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

/// State + telemetry: native -> Dart.
abstract class DualCameraFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onReady(int textureId);

  void onError(String code, String message);

  void onRecordingStarted();

  void onRecordingStopped(String path);

  void onCapabilityChanged(CameraCapabilities capabilities);

  void onThermal(ThermalLevel level);

  void onFrameStats(FrameStats stats);

  static void setUp(DualCameraFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onReady$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onReady was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_textureId = (args[0] as int?);
          assert(arg_textureId != null,
              'Argument for dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onReady was null, expected non-null int.');
          try {
            api.onReady(arg_textureId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_code = (args[0] as String?);
          assert(arg_code != null,
              'Argument for dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onError was null, expected non-null String.');
          final String? arg_message = (args[1] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onError was null, expected non-null String.');
          try {
            api.onError(arg_code!, arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onRecordingStarted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onRecordingStarted();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onRecordingStopped$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onRecordingStopped was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_path = (args[0] as String?);
          assert(arg_path != null,
              'Argument for dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onRecordingStopped was null, expected non-null String.');
          try {
            api.onRecordingStopped(arg_path!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onCapabilityChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onCapabilityChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final CameraCapabilities? arg_capabilities = (args[0] as CameraCapabilities?);
          assert(arg_capabilities != null,
              'Argument for dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onCapabilityChanged was null, expected non-null CameraCapabilities.');
          try {
            api.onCapabilityChanged(arg_capabilities!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onThermal$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onThermal was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final ThermalLevel? arg_level = (args[0] as ThermalLevel?);
          assert(arg_level != null,
              'Argument for dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onThermal was null, expected non-null ThermalLevel.');
          try {
            api.onThermal(arg_level!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onFrameStats$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onFrameStats was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final FrameStats? arg_stats = (args[0] as FrameStats?);
          assert(arg_stats != null,
              'Argument for dev.flutter.pigeon.dual_camera_recorder_platform_interface.DualCameraFlutterApi.onFrameStats was null, expected non-null FrameStats.');
          try {
            api.onFrameStats(arg_stats!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
